#!/usr/bin/env python3
"""Run one paper-reproduction trial and archive outputs."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

SPEED_GRID = [2.5, 5.0, 7.5, 10.0, 12.5]
COMPLETION_MARKERS = ("Tracking complete", "No more references will be received")
DEFAULT_TIMEOUT_S = 3600
POST_COMPLETE_GRACE_S = 5

TRAJ_MODES = {
    "circle": {
        "mode": "loop",
        "traj_name": "circle",
        "template": "traj_circle.yaml",
        "loop_r": 5.0,
        "loop_z": 2.5,
    },
    "wrapped_circle": {
        "mode": "wraped_loop",
        "traj_name": "wraped_circle",
        "template": "traj_wraped_circle.yaml",
        "loop_r": 4.5,
        "loop_z": 3.0,
    },
    "lemniscate": {
        "mode": "lemniscate",
        "traj_name": "lemniscate",
        "template": "traj_lemniscate.yaml",
        "loop_r": 7.5,
        "loop_z": 2.5,
    },
    "wrapped_lemniscate": {
        "mode": "wraped_lemniscate",
        "traj_name": "wraped_lemniscate",
        "template": "traj_wraped_lemniscate.yaml",
        "loop_r": 7.5,
        "loop_z": 3.0,
    },
    "letter_zyy": {"traj_name": "letter_zyy", "letter": "zyy", "is_letter": True},
}

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))
from algorithm_registry import ALGO_REGISTRY, ALL_ALGORITHMS, get_algo  # noqa: E402


def repo_paths() -> dict[str, Path]:
    script_dir = Path(__file__).resolve().parent
    pkg_dir = script_dir.parent
    ws_root = pkg_dir.parent.parent
    return {
        "pkg": pkg_dir,
        "ws": ws_root,
        "config": pkg_dir / "config",
        "data_mat": pkg_dir / "data" / "mat",
        "data_logs": pkg_dir / "data" / "logs",
        "data_results": pkg_dir / "data" / "results",
        "ros_mpc_benchmark": ws_root / "src" / "SSI-MPC" / "ros_mpc" / "benchmark",
        "ros_mpc_results_data": ws_root / "src" / "SSI-MPC" / "ros_mpc" / "results" / "data",
        "ros_mpc_config": ws_root / "src" / "SSI-MPC" / "ros_mpc" / "config",
    }


def write_traj_yaml(paths: dict[str, Path], traj: str, v_max: float) -> Path:
    meta = TRAJ_MODES[traj]
    template_path = paths["ros_mpc_config"] / meta["template"]
    template = template_path.read_text(encoding="utf-8")

    out_dir = paths["config"] / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{traj}_v{v_max}.yaml"

    lines = []
    for line in template.splitlines():
        if line.startswith("mode:"):
            lines.append(f'mode: "{meta["mode"]}"')
        elif line.startswith("loop_v_max:"):
            lines.append(f"loop_v_max: {v_max:.1f}       # generated by paper_reproduction")
        else:
            lines.append(line)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def parse_rmse(log_text: str) -> float | None:
    match = re.search(r"Total RMSE:\s+([0-9.]+)\s+m", log_text)
    if match:
        return float(match.group(1))
    match = re.search(r"Tracking RMSE:\s+([0-9.]+)\s+m", log_text)
    if match:
        return float(match.group(1))
    return None


def archive_mat(paths: dict[str, Path], algo: str, traj: str, v_max: float, trial: int) -> None:
    src = find_completed_mat(paths, algo, traj, v_max)
    if src is None:
        print(f"[warn] expected mat file not found under benchmark/ or results/data/")
        return

    dst_dir = paths["data_mat"] / algo / traj
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / f"trial{trial:02d}_v{v_max:.1f}.mat"
    shutil.copy2(src, dst)
    print(f"[info] archived {src.name} -> {dst}")


def _launch_arg(key: str, value: str | int | float | bool) -> str:
    if isinstance(value, bool):
        return f"{key}:={'true' if value else 'false'}"
    return f"{key}:={value}"


def is_letter_trajectory(traj: str) -> bool:
    return TRAJ_MODES[traj].get("is_letter", False)


def build_launch_cmd(
    paths: dict[str, Path],
    algo: str,
    trajectory: str,
    v_max: float,
    traj_yaml: Path | None,
    plot: bool,
    gp_model_version: str | None,
    gp_model_name: str | None,
    rdrv_model_version: str | None = None,
    rdrv_model_name: str | None = None,
) -> list[str]:
    spec = get_algo(algo)
    letter = is_letter_trajectory(trajectory)
    common = [
        f"plot:={'true' if plot else 'false'}",
        "save_data:=true",
        "recording:=false",
    ]
    if letter:
        meta = TRAJ_MODES[trajectory]
        common.extend(
            [
                f"letter:={meta['letter']}",
                f"loop_v_max:={v_max:.1f}",
                "loop_z:=2.5",
                "loop_lin_a:=0.25",
                "letter_scale:=1.15",
                "letter_center_x:=8.0",
                "letter_center_y:=0.0",
            ]
        )
    elif traj_yaml is not None:
        common.insert(0, f"traj_config:={traj_yaml}")

    if spec.family == "mpc":
        launch_file = (
            paths["pkg"] / "launch" / ("mpc_letter_repro.launch" if letter else "mpc_repro.launch")
        )
        cmd = ["roslaunch", str(launch_file), *common]
        for key, value in spec.launch_args.items():
            cmd.append(_launch_arg(key, value))
        return cmd

    if spec.family == "gpmpc":
        model_type = str(spec.launch_args.get("model_type", "gp"))
        if model_type == "rdrv":
            version = rdrv_model_version or gp_model_version
            name = rdrv_model_name or "gazebo_sim_rdrv"
            if not version:
                raise ValueError("RDRv-MPC requires --rdrv-model-version or --gp-model-version")
        else:
            version = gp_model_version
            name = gp_model_name or "gazebo_sim_gp"
            if not version:
                raise ValueError("GP-MPC requires --gp-model-version")

        launch_file = (
            paths["pkg"] / "launch" / ("gp_mpc_letter_repro.launch" if letter else "gp_mpc_repro.launch")
        )
        cmd = [
            "roslaunch",
            str(launch_file),
            *common,
            f"model_version:={version}",
            f"model_name:={name}",
            f"model_type:={model_type}",
        ]
        for key, value in spec.launch_args.items():
            if key == "model_type":
                continue
            cmd.append(_launch_arg(key, value))
        return cmd

    raise ValueError(f"unsupported algorithm family: {spec.family}")


def expected_mat_name(algo: str, traj: str, v_max: float) -> str:
    meta = TRAJ_MODES[traj]
    prefix = get_algo(algo).mat_prefix
    return f"{prefix}_{meta['traj_name']}_{v_max:.1f}.mat"


def mat_search_paths(paths: dict[str, Path], algo: str, traj: str, v_max: float) -> list[Path]:
    name = expected_mat_name(algo, traj, v_max)
    candidates = [paths["ros_mpc_benchmark"] / name]
    if get_algo(algo).family == "gpmpc":
        candidates.append(paths["ros_mpc_results_data"] / name)
    return candidates


def expected_mat_path(paths: dict[str, Path], algo: str, traj: str, v_max: float) -> Path:
    return mat_search_paths(paths, algo, traj, v_max)[0]


def find_completed_mat(paths: dict[str, Path], algo: str, traj: str, v_max: float) -> Path | None:
    for candidate in mat_search_paths(paths, algo, traj, v_max):
        if candidate.exists() and candidate.stat().st_size > 1000:
            return candidate
    return None


def estimate_timeout_s(v_max: float, trajectory: str, lin_acc: float = 0.25) -> int:
    if is_letter_trajectory(trajectory):
        # ZYY combined path ~3× single letter
        sim_duration = 3 * (2 * v_max / lin_acc + 8)
        return int(sim_duration * 2.2 + 240)
    # trajectories.py: t_total = 2*v/lin_acc + 4; Gazebo ~50% speed; plus fly-to-start after prior trial.
    sim_duration = 2 * v_max / lin_acc + 4
    traj_factor = 1.0
    if trajectory in ("lemniscate", "wrapped_lemniscate"):
        traj_factor = 1.6
    if trajectory in ("wrapped_circle", "wrapped_lemniscate"):
        traj_factor += 0.4
    approach_margin = 240
    return int(sim_duration * 2.8 * traj_factor + approach_margin)


def archived_mat_path(paths: dict[str, Path], algo: str, traj: str, v_max: float, trial: int) -> Path:
    return paths["data_mat"] / algo / traj / f"trial{trial:02d}_v{v_max:.1f}.mat"


def is_trial_done(paths: dict[str, Path], algo: str, traj: str, v_max: float, trial: int) -> bool:
    return archived_mat_path(paths, algo, traj, v_max, trial).exists()


def cleanup_stale_nodes() -> None:
    script = repo_paths()["pkg"] / "scripts" / "cleanup_stale_nodes.sh"
    subprocess.run(["bash", str(script)], check=False)


def _drain_output(stream, log_fp, output_chunks: list[str]) -> None:
    assert stream is not None
    for line in iter(stream.readline, ""):
        print(line, end="", flush=True)
        log_fp.write(line)
        log_fp.flush()
        output_chunks.append(line)


def run_roslaunch_until_complete(
    cmd: list[str],
    log_fp,
    mat_paths: list[Path],
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> tuple[int, str, bool]:
    """Run roslaunch; detect completion via saved .mat (stdout often misses MPC logs)."""
    for mat_path in mat_paths:
        if mat_path.exists():
            mat_path.unlink()

    start_time = time.time()
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        start_new_session=True,
    )

    output_chunks: list[str] = []
    assert proc.stdout is not None
    reader = threading.Thread(target=_drain_output, args=(proc.stdout, log_fp, output_chunks), daemon=True)
    reader.start()

    completed = False
    mat_ready_at = None
    detected_mat: Path | None = None
    deadline = time.time() + timeout_s
    mat_names = ", ".join(dict.fromkeys(p.name for p in mat_paths))
    print(f"[info] waiting for trial result (timeout {timeout_s}s, mat={mat_names})...")
    last_progress = start_time

    while proc.poll() is None:
        now = time.time()
        if now > deadline:
            print(f"[error] trial timeout after {timeout_s}s")
            break

        if now - last_progress >= 60:
            elapsed = int(now - start_time)
            print(f"[info] still running ({elapsed}s elapsed)... GP-MPC may take several minutes after ref_gen starts")
            last_progress = now

        if any(marker in chunk for chunk in output_chunks[-20:] for marker in COMPLETION_MARKERS):
            completed = True
            print(f"[info] saw completion log, stopping roslaunch in {POST_COMPLETE_GRACE_S}s...")
            time.sleep(POST_COMPLETE_GRACE_S)
            break

        for mat_path in mat_paths:
            if mat_path.exists() and mat_path.stat().st_size > 1000:
                if mat_path.stat().st_mtime < start_time - 1.0:
                    continue
                if mat_ready_at is None or detected_mat != mat_path:
                    mat_ready_at = now
                    detected_mat = mat_path
                    print(f"[info] detected {mat_path.name}, finalizing...")
                elif now - mat_ready_at >= POST_COMPLETE_GRACE_S:
                    completed = True
                    break
        if completed:
            break

        time.sleep(1.0)

    if proc.poll() is None:
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGINT)
        except ProcessLookupError:
            pass
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            proc.wait(timeout=10)

    reader.join(timeout=2)
    output = "".join(output_chunks)
    if not completed:
        print("[warn] trial may be incomplete (no mat / no Tracking complete in log)")
    return proc.returncode if proc.returncode is not None else 1, output, completed


def rearm_quad() -> None:
    script = repo_paths()["pkg"] / "scripts" / "rearm_quad.sh"
    subprocess.run(["bash", str(script)], check=False)


def wait_for_gazebo(timeout_s: int = 30) -> None:
    script = repo_paths()["pkg"] / "scripts" / "wait_for_gazebo.sh"
    proc = subprocess.run(["bash", str(script), str(timeout_s)], text=True)
    if proc.returncode != 0:
        raise SystemExit(
            "Gazebo/odometry not ready. Start terminal A first:\n"
            "  bash src/paper_reproduction/scripts/01_start_gazebo.sh\n"
            "Then click Connect + Arm Bridge in RPG Quadrotor GUI."
        )


def run_trial(args: argparse.Namespace) -> None:
    paths = repo_paths()
    paths["data_mat"].mkdir(parents=True, exist_ok=True)
    paths["data_logs"].mkdir(parents=True, exist_ok=True)
    paths["data_results"].mkdir(parents=True, exist_ok=True)

    if args.resume and is_trial_done(paths, args.algorithm, args.trajectory, args.v_max, args.trial):
        print(
            f"[skip] already done: {args.algorithm} | {args.trajectory} | v={args.v_max} | trial={args.trial}"
        )
        return 0

    if not args.skip_gazebo_check:
        wait_for_gazebo(timeout_s=30)
    cleanup_stale_nodes()
    rearm_quad()

    traj_yaml = None
    if not is_letter_trajectory(args.trajectory):
        traj_yaml = write_traj_yaml(paths, args.trajectory, args.v_max)
    cmd = build_launch_cmd(
        paths,
        args.algorithm,
        args.trajectory,
        args.v_max,
        traj_yaml,
        args.plot,
        args.gp_model_version,
        args.gp_model_name,
        args.rdrv_model_version,
        args.rdrv_model_name,
    )

    log_file = paths["data_logs"] / (
        f"{args.algorithm}_{args.trajectory}_v{args.v_max:.1f}_trial{args.trial:02d}.log"
    )

    print("[info] running:", " ".join(cmd))
    print(f"[info] log file: {log_file}")

    mat_paths = mat_search_paths(paths, args.algorithm, args.trajectory, args.v_max)
    timeout_s = args.timeout_s or estimate_timeout_s(args.v_max, args.trajectory)

    with log_file.open("w", encoding="utf-8") as log_fp:
        returncode, stdout, completed = run_roslaunch_until_complete(
            cmd, log_fp, mat_paths, timeout_s=timeout_s
        )

    if not completed:
        found = find_completed_mat(paths, args.algorithm, args.trajectory, args.v_max)
        if found is not None:
            completed = True
            print(f"[info] found completed mat after roslaunch: {found}")
        else:
            print(f"[error] trial did not complete (mat missing: {mat_paths[0]})")
            return 1

    if returncode not in (0, -2, 130):
        print(f"[warn] roslaunch exit code {returncode} (trial data may still be valid)")

    rmse = parse_rmse(stdout)
    if rmse is None and log_file.exists():
        rmse = parse_rmse(log_file.read_text(encoding="utf-8", errors="replace"))
    if rmse is not None:
        print(f"[info] parsed RMSE: {rmse:.5f} m")
        results_file = paths["data_results"] / "rmse_records.csv"
        header_needed = not results_file.exists()
        with results_file.open("a", encoding="utf-8") as fp:
            if header_needed:
                fp.write("timestamp,algorithm,trajectory,v_max,trial,rmse_m\n")
            fp.write(
                f"{int(time.time())},{args.algorithm},{args.trajectory},{args.v_max:.1f},"
                f"{args.trial},{rmse:.6f}\n"
            )
    else:
        print("[warn] could not parse RMSE from log")

    archive_mat(paths, args.algorithm, args.trajectory, args.v_max, args.trial)
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Run one SSI-MPC paper reproduction trial.")
    parser.add_argument(
        "--algorithm",
        required=True,
        choices=ALL_ALGORITHMS,
        help="controller variant (see scripts/algorithm_registry.py)",
    )
    parser.add_argument(
        "--trajectory",
        required=True,
        choices=list(TRAJ_MODES.keys()),
    )
    parser.add_argument("--v-max", type=float, required=True, help="loop_v_max in yaml, e.g. 10.0")
    parser.add_argument("--trial", type=int, default=1, help="trial index for archiving (1..N)")
    parser.add_argument("--plot", action="store_true", help="show matplotlib tracking plots")
    parser.add_argument("--gp-model-version", default="", help="git hash folder under ros_mpc/results/model_fitting/")
    parser.add_argument("--gp-model-name", default="gazebo_sim_gp", help="GP model name")
    parser.add_argument("--rdrv-model-version", default="", help="RDRv model git hash (defaults to gp-model-version)")
    parser.add_argument("--rdrv-model-name", default="gazebo_sim_rdrv", help="RDRv model name")
    parser.add_argument(
        "--skip-gazebo-check",
        action="store_true",
        help="skip odometry preflight (not recommended)",
    )
    parser.add_argument(
        "--timeout-s",
        type=int,
        default=0,
        help="max seconds per trial (0 = auto from v-max and trajectory)",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="skip if archived mat already exists under data/mat/",
    )
    args = parser.parse_args()
    raise SystemExit(run_trial(args))


if __name__ == "__main__":
    main()
